//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NeuroStudio.rc
//
#define IDD_ABOUTBOX                    100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_NeuroStockTYPE              130
#define IDS_WINDOWS_MANAGER             132
#define IDC_PROPERTIESWND               133
#define IDC_DESIGNERRORWND              134
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DEFINE_CSV_DLG              311
#define IDR_GRAPH_MENU                  312
#define IDD_STREAM                      314
#define IDD_DEFINE_STREAM               316
#define IDD_SIMULATION_DISPLAY          320
#define IDD_SIMULATION                  320
#define IDD_TEXT_FILTER_FORMAT          321
#define IDD_LAYER_DEFINE                324
#define IDD_IMAGE_TEST                  325
#define IDD_DATA_PRODUCER_DEFINE        335
#define IDD_SIM_TRAIN_SETUP             346
#define IDD_SIM_RUN_SETUP               347
#define IDB_DROPOUT_PLANE               351
#define IDB_RNN_PLANE                   352
#define IDB_BN_PLANE                    353
#define IDB_LRCN_PLANE                  354
#define IDD_TARGET_PRODUCER_CLASS_RANGE 355
#define IDB_CONCAT_PLANE                355
#define IDD_SIM_RUNNING                 360
#define IDB_1D_1SHAPE                   501
#define IDB_1DSHAPE                     502
#define IDB_2DSHAPE                     503
#define IDB_3DSHAPE                     504
#define IDB_CONV_PLANE                  505
#define IDB_POOL_PLANE                  506
#define IDB_FULLY_PLANE                 507
#define IDC_SIM_INPUT_WND               1001
#define IDC_SIM_OUTPUT_WND              1002
#define IDC_SIM_TARGET_WND              1003
#define IDC_SIM_PARAM_WND               1004
#define IDC_INPUT_LIST                  1038
#define IDC_OUTPUT_LIST                 1040
#define IDC_TARGET_MAKER_BTN            1041
#define IDC_STATIC_FIXED_COUNT          1043
#define IDC_INPUT_DISPLAY_COMBO         1044
#define IDC_OUTPUT_DISPLAY_COMBO        1045
#define IDC_INPUT_DISPLAY_TREE          1046
#define IDC_OUTPUT_DISPLAY_TREE         1047
#define IDC_BUTTON_ARRANGE_DISPLAY      1050
#define IDC_EDIT_TRAIN_FULL_LOOP_COUNT  1051
#define IDC_EDIT_TRAIN_SEQ_LOOP_COUNT   1052
#define IDC_START_SEQ_EDIT              1055
#define IDC_PARAM_DISPLAY_TREE          1056
#define IDC_BUTTON_ADD_ITEM             1059
#define IDC_BUTTON_NEW                  1061
#define IDC_COMBO_RETVALUE              1063
#define IDC_BUTTON_FILTER_CHANGE        1065
#define IDC_EDIT_IMPORTED_DATA          1072
#define IDC_EDIT_TYPE_WIDTH             1073
#define IDC_EDIT_IMPORTED_COUNT         1075
#define IDC_EDIT_TYPE_HEIGHT            1076
#define IDC_STATIC_INPUT_DESC           1080
#define IDC_EDIT_POOL_WIDTH             1082
#define IDC_EDIT_POOL_SIZE              1083
#define IDC_EDIT_POOL_STRIDE            1084
#define IDC_SEL_DATA                    1085
#define IDC_MAKE_DATA                   1086
#define IDC_DATA_TREE                   1087
#define IDC_TRAIN_RADIO                 1088
#define IDC_RUN_RADIO                   1089
#define IDC_IMG_VIEW                    1090
#define IDC_EDIT_TENSOR                 1091
#define IDC_TREE_COMPOSITE_MULTI_STREAM 1202
#define IDC_TREE_BUILT_STREAM           1203
#define IDC_STATIC_CONTENT              1215
#define IDC_BUTTON_EDIT_CONTENT         1216
#define IDC_EDIT_MAX_EPOCH              1232
#define IDC_TREE_DATA                   1233
#define IDC_EDIT_BATCH_SIZE             1233
#define IDC_SIM_RUN_EDIT                1234
#define IDC_SIM_RUN_PAINT               1235
#define IDC_EDIT_BELOW_ERROR            1236
#define IDC_EDIT_DISPLAY_PERIOD         1237
#define IDC_BUTTON_START                1239
#define IDC_BUTTON_STOP                 1240
#define IDC_RADIO_DRAW                  1241
#define IDC_BUTTON_STOP_EPOCH           1241
#define IDC_RADIO_TEXT                  1242
#define IDC_RADIO_FILE                  1243
#define IDC_RADIO_TRAIN                 1244
#define IDC_RADIO_RUN                   1245
#define IDC_RADIO_PARALLEL_CUDA         1246
#define IDC_RADIO_PARALLEL_CPU          1247
#define IDC_STATIC_MAX_EPOCH            1248
#define IDC_STATIC_DATA                 1249
#define IDC_STATIC_NO_PREFIX            1249
#define IDC_STATIC_MINIBATCH_INFO       1250
#define IDC_STATIC_DISPLAY_PERIOD       1251
#define IDC_STATIC_ANALYSYS             1252
#define IDC_STATIC_IMPORT               1261
#define IDC_STATIC_TYPE_WIDTH           1266
#define IDC_STATIC_TYPE_HEIGHT          1268
#define IDC_BUTTON_UNDO                 1276
#define IDC_EDIT_RATE2                  1282
#define IDC_STATIC_PARALLEL_DEVICE      1284
#define IDC_CHECK_INIT_WEIGHTS          1286
#define IDC_CHECK_BELOW_ERROR           1287
#define IDC_STATIC_END_CONDITION        1288
#define IDC_CHECK_TEST_AFTER_LEARN      1289
#define IDC_STATIC_DISPLAY              1290
#define IDC_STATIC_BATCH_SIZE           1291
#define IDC_CHECK_ANALYZE_ARGMAX_ACCURACY 1292
#define IDC_CHECK_ANALYZE_LOSS_HISTORY  1293
#define IDC_CHECK_USE_NDF               1294
#define IDC_CHECK_USE_NDF2              1295
#define IDC_CHECK_DATA_NOISING          1295
#define IDC_PROVIDER_WND                1500
#define IDC_NN_DESIGN_WND               1501
#define IDC_SIM_SETUP_WND               1502
#define IDC_SIM_DISPLAY_WND             1503
#define IDC_INPUT_PROVIDER_WND          1600
#define IDC_TRAIN_INPUT_PROVIDER_WND    1601
#define IDC_TRAIN_TARGET_PROVIDER_WND   1602
#define IDC_OUTPUT_TENSOR_WND           1603
#define IDC_TRAIN_SETUP_WND             1604
#define IDC_CHECK_USE_PAD               1611
#define IDC_CHECK_DEFAULT_MNIST         1612
#define IDC_STATIC_NOTICE_DIFF_TENSOR   1613
#define IDC_BUTTON_FIT_IO               1616
#define IDC_STATIC_FIT_IO_TENSOR        1617
#define IDC_STATIC_IO_TENSOR_LABEL      1618
#define IDC_LIST_SEL_CONCAT_AXIS        1619
#define IDC_BUTTON_CLEAR                1625
#define IDC_RADIO_TRAIN_TEST            1633
#define IDC_RADIO_TRAIN_LEARN           1634
#define IDC_LIST_MORPH_ANALYZER         1644
#define IDC_DATA_GROUP                  1654
#define IDC_CHECK_SHUFFLE               1657
#define IDC_STATIC_OUTPUT               1662
#define IDC_EDIT_OUTPUT_FILEPATH        1663
#define IDC_EDIT_OUTPUT_NO_PREFIX       1664
#define IDC_STATIC_FILE_PATH            1665
#define IDC_TAB_SIM_DISPLAY             1675
#define IDC_ANALYSIS                    1676
#define IDC_LAYER_DISPLAY               1677
#define IDC_ONEHOT_RESULT_LIST          1678
#define IDC_PROP_LIST                   1900
#define IDS_MENU_LINK_DEL               2000
#define IDS_MENU_MODEL_DEL              2001
#define IDS_MENU_LAYER_ADD              2100
#define IDS_MENU_ADD_OUTPUT_LAYER       2101
#define IDS_MENU_LAYER_MULTI_DEL        2102
#define IDS_MENU_BIN_READER_ADD_TO_INPUT 2200
#define IDS_MENU_TEXT_READER_ADD_TO_INPUT 2201
#define IDS_MENU_PRODUCER_ADD           2202
#define IDS_MENU_DISPLAY_DEL            2300
#define IDS_MENU_ADD_DISPLAY_LAYER_ALL  2301
#define IDS_MENU_CLEAR_ALL_DISPLAY_LAYER 2302
#define IDS_ADD_ITEM                    3000
#define IDS_DEL_ITEM                    3001
#define ID_NEURALNETWORK_OPEN           5002
#define ID_NEURALNETWORK_SAVE           5003
#define ID_SOURCE_ADD_COLUMN_ITEM       5006
#define ID_SOURCE_DEL_ITEM              5007
#define ID_NEURALNETWORK_REPLACE        5007
#define ID_VIEW_PROPERTIES_WND          5009
#define ID_VIEW_ERROR_WND               5010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        360
#define _APS_NEXT_COMMAND_VALUE         5011
#define _APS_NEXT_CONTROL_VALUE         1679
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
