image: Visual Studio 2015

platform:
- x64

environment:
  matrix:
    - BUILD_TYPE: x86
    - BUILD_TYPE: x64

build_script:
    - cd src
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %BUILD_TYPE%
    - nmake -f Makefile.%BUILD_TYPE%.msvc.in
    
after_build:
    - cd %APPVEYOR_BUILD_FOLDER%\
    - 7z a mecab-ko-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\src\*.dll
    - 7z a mecab-ko-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\src\*.exe
    - 7z a mecab-ko-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\src\*.lib
    - 7z a mecab-ko-msvc-%BUILD_TYPE%.zip %APPVEYOR_BUILD_FOLDER%\src\mecab.h

artifacts: 
  - path: '*.zip'
    name: MeCab-KO-MSVC
deploy:
  description: 'MeCab-Ko-MSVC'
  provider: GitHub
  auth_token:
    secure: OmfpZhJdq1DA5Yl/KrpU0VVV6jCM7DQ/8gH7IH1Fld9TtRvnHCTLxJSTXVgsOEmJ
  artifact: MeCab-KO-MSVC    
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
